void isB0Pressed();
void enableButton(int);
int buttonPushed(int);
int buttonReleased(int);
void enableAllButtons();
void generatePuzzle(uint8_t[], int);
void printPuzzle(uint8_t[], int);
int readInput(uint8_t, int);
int anyButtonPushed();
int buttonPressed(int button);
int buttonClicked(int button);